{{- if not .Values.tls.keystoreSecret }}
---
apiVersion: v1
data:
  client.keystore: MGUCAQMwEQYJKoZIhvcNAQcBoAQEAjAAME0wMTANBglghkgBZQMEAgEFAAQgif7weCrllradyatMOq+yff/V2XMNbjPKif/PI8z6RAcEFIl3tRkux/5fzMYF/H/eV/DuUvm0AgInEA==
kind: Secret
metadata:
  namespace: {{ include "common.namespace" . | quote }}
  labels: {{- include "common.labels" . | nindent 4 }}
    app.kubernetes.io/component: orchestrator
  name: {{ printf "%s-blank-keystore" (include "common.name" .) }}
{{- end }}