{{- if .Values.issuer.enabled }}
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  namespace: {{ include "common.namespace" . | quote }}
  labels: {{- include "common.labels" . | nindent 4 }}
    app.kubernetes.io/component: orchestrator
  name: {{ default (printf "%s-issuer" (include "common.name" .)) .Values.issuer.name  }}
spec:
  acme:
    email: {{ .Values.issuer.email }}
    preferredChain: ""
    privateKeySecretRef:
      name: issuer-account-key
    server: {{ .Values.issuer.server }}
    solvers:
    {{- if .Values.issuer.solvers }}
        {{- include "common.render" (dict "value" .Values.issuer.solvers "context" $) | nindent 8 }}
    {{- else }}
        - http01:
            ingress:
                class: traefik
    {{- end }}
{{- end }}