---
apiVersion: v1
data:
  db.cnf: |-
    [mysqld]
    skip-name-resolve
    max_connections = 600
    connect_timeout = 1200
    net_read_timeout = 1800
    net_write_timeout = 1800
    max_allowed_packet = 512M
    interactive_timeout = 1000000
    wait_timeout = 1000000
    explicit_defaults_for_timestamp = 1
    default-time-zone = "+00:00"
kind: ConfigMap
metadata:
  namespace: {{ include "common.namespace" . | quote }}
  labels: {{- include "common.labels" . | nindent 4 }}
    app.kubernetes.io/component: mysql
  name: {{ printf "%s-mysql-config" (include "common.name" .) }}
