{{- if .Values.mysql.generatePVC }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: {{ include "common.namespace" . | quote }}
  annotations:
    helm.sh/resource-policy: "keep"
  labels: {{- include "common.labels" . | nindent 4 }}
    app.kubernetes.io/component: mysql
  name: {{ default (printf "%s-mysql-pvc" (include "common.name" .)) .Values.mysql.pvcName }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  {{- if .Values.global.mode "test" }}
  {{- else }}
  storageClassName: {{.Values.mysql.pvcClass}}
  {{- end }}
{{- end }}