---
apiVersion: v1
kind: Service
metadata:
  namespace: {{ include "common.namespace" . | quote }}
  labels:
    stackv/service: orchestrator
  name: {{.Release.Name}}-mysql
spec:
  ports:
    - name: port-3306
      port: 3306
      protocol: TCP
      targetPort: 3306
  selector:
    stackv/service: orchestrator
    app.kubernetes.io/name: {{.Release.Name}}-mysql
  type: ClusterIP
