apiVersion: v1
data:
  all_dump.sql: ""
kind: ConfigMap
metadata:
  namespace: {{ include "common.namespace" . | quote }}
  labels: {{- include "common.labels" . | nindent 4 }}
    app.kubernetes.io/component: mysql
  name: {{.Release.Name}}-mysql-init-dump
