apiVersion: v1
data:
  all_dump.sql: ""
kind: ConfigMap
metadata:
  namespace: {{ include "common.namespace" . | quote }}
  labels:
    stackv/service: mysql
    stackv/stack: app
  name: {{.Release.Name}}-mysql-init-dump
