---
apiVersion: v1
kind: Service
metadata:
  namespace: {{ include "common.namespace" . | quote }}
  labels: {{- include "common.labels" . | nindent 4 }}
    app.kubernetes.io/component: orchestrator
  name: {{ printf "%s-orch" (include "common.name" .) }}
spec:
  type: {{ .Values.service.type }}
  ipFamilyPolicy: PreferDualStack
  ports:
    - port: {{ .Values.service.ports.https }}
      protocol: TCP
      targetPort: app-https
      name: https
    - port: {{ .Values.service.ports.http }}
      protocol: TCP
      targetPort: app-http
      name: http
    {{- if .Values.service.ports.debug.enabled }}            
    - port: 9990
      protocol: TCP
      targetPort: console-http
      name: console-http
    - port: 9993
      protocol: TCP
      targetPort: console-https
      name: console-https
    - port: 8787
      protocol: TCP
      targetPort: app-debug
      name: debug
    {{- end }}
  selector: {{- include "common.labels.match" . | nindent 4 }}
    app.kubernetes.io/component: orchestrator