---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ include "common.namespace" . | quote }}
  labels: {{- include "common.labels" . | nindent 4 }}
    app.kubernetes.io/component: orchestrator
  name: {{.Release.Name}}-orch
spec:
  replicas: 1
  revisionHistoryLimit: 3
  minReadySeconds: 10
  selector:
    matchLabels: {{ include "common.labels.match" . | nindent 6 }}
      app.kubernetes.io/component: orchestrator
  template:
    metadata:
      annotations:
        stackv/tag: {{ .Values.image.tag | default .Chart.AppVersion }}
        link.argocd.argoproj.io/external-link: https://{{ .Values.ingress.hostname | default .Values.global.domain }}/StackV-web/portal/
      labels: {{- include "common.labels" . | nindent 8 }}
        app.kubernetes.io/component: orchestrator
      name: {{ .Release.Name }}-orch
    spec:
      {{- with .Values.image.pullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - image: "{{ .Values.image.repo }}:{{ default .Chart.AppVersion .Values.image.tag }}"
          imagePullPolicy: Always
          args:
            - /bin/wait-for-it.sh
            - {{ .Release.Name }}-mysql:3306
            - "-t"
            - "600"
            - "-s"
            - "--"
            - sh
            - "-c"
            - /bin/startup.sh
          env:
            - name: KC_DOMAIN
              value: "{{.Values.global.keycloak}}"
            - name: NO_SERVER_KEYSTORE
              value: "true"
            - name: DB_HOST
              value: "{{.Release.Name}}-mysql:3306"
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.global.credSecret }}
                  key: {{ .Values.mysql.passwordKey }}
            - name: TLS_PASS
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.global.credSecret }}
                  key: {{.Values.tls.passwordKey}}
            - name: MAIL_PORT
              value: "{{.Values.mail.port}}"
            - name: MAIL_HOST
              value: "{{.Values.mail.host}}"
            - name: MAIL_USER
              value: "{{.Values.mail.username}}"
            - name: MAIL_PASS
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.global.credSecret }}
                  key: {{ .Values.mail.passwordKey }}
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}    
          {{- if .Values.probes.startup.enabled }}
          startupProbe:
            httpGet:
              path: /
              port: 8080
            failureThreshold: 24
            initialDelaySeconds: 60
            periodSeconds: 15
            successThreshold: 1
            timeoutSeconds: 5
          {{- else if .Values.probes.startup.custom }}
          startupProbe: {{- include "common.render" (dict "value" .Values.probes.startup.custom "context" $) | nindent 12 }}
          {{- end }}
          {{- if .Values.probes.liveness.enabled }}
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            failureThreshold: 6
            periodSeconds: 15
            successThreshold: 1
            timeoutSeconds: 5
          {{- else if .Values.probes.liveness.custom }}
          livenessProbe: {{- include "common.render" (dict "value" .Values.probes.liveness.custom "context" $) | nindent 12 }}
          {{- end }}
          {{- if .Values.probes.readiness.enabled }}
          readinessProbe:
            httpGet:
              scheme: HTTPS
              path: /StackV-web/portal/
              port: 8443
            failureThreshold: 9
            initialDelaySeconds: 60
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 60
          {{- else if .Values.probes.readiness.custom }}
          readinessProbe: {{- include "common.render" (dict "value" .Values.probes.readiness.custom "context" $) | nindent 12 }}
          {{- end }}        
          name: {{.Release.Name}}-orchestrator
          ports:
            - containerPort: 8443
              name: app-https
              protocol: TCP
            - containerPort: 8080
              name: app-http
              protocol: TCP
            - containerPort: 9990
              name: console-http
              protocol: TCP
            - containerPort: 9993
              name: console-https
              protocol: TCP
            - containerPort: 8787
              name: app-debug
              protocol: TCP
          volumeMounts:
            - mountPath: /opt/jboss/wildfly/standalone/configuration/tls
              name: client-keystore
      restartPolicy: Always
      volumes:
        - secret:
            secretName: {{ .Values.tls.keystoreSecret }}
          name: client-keystore
      {{- if .Values.affinity }}
      affinity: {{- include "common.render" ( dict "value" .Values.affinity "context" $) | nindent 8 }}
      {{- end }}
      {{- if .Values.nodeSelector }}
      nodeSelector: {{- include "common.render" ( dict "value" .Values.nodeSelector "context" $) | nindent 8 }}
      {{- end }}
      {{- if .Values.tolerations }}
      tolerations: {{- include "common.render" (dict "value" .Values.tolerations "context" .) | nindent 8 }}
      {{- end }}