{{- $orchName := printf "%s-orch" (include "common.name" .) }}
{{- $mysqlName := printf "%s-mysql" (include "common.name" .) }}
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: {{ include "common.namespace" . | quote }}
  labels: {{- include "common.labels" . | nindent 4 }}
    app.kubernetes.io/component: orchestrator
  name: {{ $orchName }}
spec:
  replicas: 1
  revisionHistoryLimit: 3
  minReadySeconds: 10
  selector:
    matchLabels: {{ include "common.labels.match" . | nindent 6 }}
      app.kubernetes.io/component: orchestrator
  template:
    metadata:
      annotations:
        stackv/tag: {{ .Values.image.tag | default .Chart.AppVersion }}
        link.argocd.argoproj.io/external-link: https://{{ .Values.ingress.hostname | default .Values.global.domain }}/StackV-web/portal/
      labels: {{- include "common.labels" . | nindent 8 }}
        app.kubernetes.io/component: orchestrator
      name: {{ $orchName }}
    spec:
      {{- with .Values.image.pullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.init.enabled }}
      initContainers:
        {{- if .Values.init.migration.enabled }}
        - name: "{{ $orchName }}-db-init-frontend"
          image: "{{ .Values.init.migration.repository }}:{{ splitList "@" (default .Chart.AppVersion (default .Values.image.tag .Values.init.migration.tag)) | first }}-frontend"
          imagePullPolicy: Always
          args: ["deploy", "-t", "db:mysql://$(SQITCH_USER):$(SQITCH_PASSWORD)@$(SQITCH_DB_HOST)/frontend"]
          env:
            - name: SQITCH_USER
              value: "root"
            - name: SQITCH_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.global.credSecret }}
                  key: {{ .Values.mysql.passwordKey }}
            - name: SQITCH_DB_HOST
              value: "{{ $mysqlName }}:3306"
        - name: "{{ $orchName }}-db-init"
          image: "{{ .Values.init.migration.repository }}:{{ splitList "@" (default .Chart.AppVersion (default .Values.image.tag .Values.init.migration.tag)) | first }}"
          imagePullPolicy: Always
          args: ["deploy", "-t", "db:mysql://$(SQITCH_USER):$(SQITCH_PASSWORD)@$(SQITCH_DB_HOST)/rainsdb"]
          env:
            - name: SQITCH_USER
              value: "root"
            - name: SQITCH_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.global.credSecret }}
                  key: {{ .Values.mysql.passwordKey }}
            - name: SQITCH_DB_HOST
              value: "{{ $mysqlName }}:3306"
        {{- end }}
      {{- end }}
      containers:
        - image: "{{ .Values.image.repository }}:{{ default .Chart.AppVersion .Values.image.tag }}"
          imagePullPolicy: Always
          command:
          - sh
          - -c
          - |
            /bin/wait-for-it.sh {{ $mysqlName }}:3306 -t 600 -s -- /bin/startup.sh
          env:
            - name: KC_DOMAIN
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.auth.clientSecret }}
                  key: host
            - name: KC_CLIENT
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.auth.clientSecret }}
                  key: client
            - name: KC_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.auth.clientSecret }}
                  key: client-secret
            - name: NO_SERVER_KEYSTORE
              value: "true"
            - name: DB_HOST
              value: "{{ $mysqlName }}:3306"
            - name: JAVA_MEMORY
              value: "{{ .Values.java.memory }}"
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.global.credSecret }}
                  key: {{ .Values.mysql.passwordKey }}
            - name: TLS_PASS
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.global.credSecret }}
                  key: {{.Values.tls.passwordKey}}
            - name: MAIL_PORT
              value: "{{.Values.mail.port}}"
            - name: MAIL_HOST
              value: "{{.Values.mail.host}}"
            - name: MAIL_USER
              value: "{{.Values.mail.username}}"
            - name: MAIL_PASS
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.global.credSecret }}
                  key: {{ .Values.mail.passwordKey }}
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}    
          {{- if .Values.probes.startup.enabled }}
          startupProbe:
            httpGet:
              path: /
              port: 8080
            failureThreshold: 30
            initialDelaySeconds: 180
            timeoutSeconds: 10
          {{- else if .Values.probes.startup.custom }}
          startupProbe: {{- include "common.render" (dict "value" .Values.probes.startup.custom "context" $) | nindent 12 }}
          {{- end }}
          {{- if .Values.probes.liveness.enabled }}
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            failureThreshold: 6
            timeoutSeconds: 15
          {{- else if .Values.probes.liveness.custom }}
          livenessProbe: {{- include "common.render" (dict "value" .Values.probes.liveness.custom "context" $) | nindent 12 }}
          {{- end }}
          {{- if .Values.probes.readiness.enabled }}
          readinessProbe:
            httpGet:
              path: /StackV-web/portal/
              port: 8080
            timeoutSeconds: 15
            initialDelaySeconds: 15
          {{- else if .Values.probes.readiness.custom }}
          readinessProbe: {{- include "common.render" (dict "value" .Values.probes.readiness.custom "context" $) | nindent 12 }}
          {{- end }}        
          name: {{ $orchName }}
          ports:
            - containerPort: 8443
              name: app-https
              protocol: TCP
            - containerPort: 8080
              name: app-http
              protocol: TCP
            - containerPort: 9990
              name: console-http
              protocol: TCP
            - containerPort: 9993
              name: console-https
              protocol: TCP
            - containerPort: 8787
              name: app-debug
              protocol: TCP
          volumeMounts:
            - mountPath: /opt/jboss/wildfly/standalone/configuration/tls
              name: client-keystore
      restartPolicy: Always
      volumes:
        - secret:
            secretName: {{ default (printf "%s-blank-keystore" (include "common.name" .)) .Values.tls.keystoreSecret }}
          name: client-keystore
      {{- if .Values.affinity }}
      affinity: {{- include "common.render" ( dict "value" .Values.affinity "context" $) | nindent 8 }}
      {{- end }}
      {{- if .Values.nodeSelector }}
      nodeSelector: {{- include "common.render" ( dict "value" .Values.nodeSelector "context" $) | nindent 8 }}
      {{- end }}
      {{- if .Values.tolerations }}
      tolerations: {{- include "common.render" (dict "value" .Values.tolerations "context" .) | nindent 8 }}
      {{- end }}