---
apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Values.global.namespace }}
  labels:
    stackv/service: orchestrator
    stackv/stack: app
  name: {{.Release.Name}}-orchestrator
spec:
  type: {{ .Values.service.type }}
  ipFamilyPolicy: PreferDualStack
  ports:
    - port: {{ .Values.service.ports.https }}
      protocol: TCP
      targetPort: app-https
      name: https
    - port: {{ .Values.service.ports.http }}
      protocol: TCP
      targetPort: app-http
      name: http
    {{- if .Values.service.ports.debug.enabled }}            
    - port: 9990
      protocol: TCP
      targetPort: console-http
      name: console-http
    - port: 9993
      protocol: TCP
      targetPort: console-https
      name: console-https
    - port: 8787
      protocol: TCP
      targetPort: app-debug
      name: debug
    {{- end }}
  selector:
    stackv/service: orchestrator
    app.kubernetes.io/name: {{.Release.Name}}-orchestrator
