apiVersion: v2
name: sense-keycloak
description: Keycloak pre-configured for the SENSE Orchestrator.

icon: https://www.keycloak.org/resources/images/icon.svg

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 1.0.0

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
# It is recommended to use it with quotes.
appVersion: "26.6.1"

dependencies:
  - name: keycloakx
    version: 7.1.11
    repository: https://codecentric.github.io/helm-charts
    condition: keycloakx.enabled
  - name: postgresql
    version: 18.6.1
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
  - name: sense-commons
    version: 1.x.x
    repository: https://stackv.github.io/sense-helm/
