### SENSE Keycloak Configuration
###

## @section Global Parameters
##
#
global:
  ## @param global.domain The host domain. Can be used for the Ingress hostname such as `keycloak.{{ .Values.global.domain }}`
  domain: example.es.net
  #
  security:
    ## @skip global.security.allowInsecureImages Bitnami image validator.
    allowInsecureImages: true

## @section Common Parameters
##
#
## @param namespaceOverride Override for the Helm namespace.
namespaceOverride:
## @param nameOverride Override for the Chart name.
nameOverride: sense-kc

## @section PostgreSQL Parameters
##
#
postgres:
  ## @param postgres.enabled Whether to enable the included postgres deployment.
  enabled: true
  ## @param postgres.database The cluster init database name.
  database: keycloak
  ## @param postgres.secret The secret with the database password specified.
  secret: "{{ .Release.Name }}-psql-auth"
  ## @param postgres.pvcClass PVC class for the PSQL persistence.
  pvcClass: local-path
  ## @param postgres.existingPVC Specify an existing PVC to use.
  existingPVC:
  #
  probes:
    startup:
      ## @param postgres.probes.startup.enabled Whether to enable the default PSQL startup probe.
      enabled: true
      ## @param postgres.probes.startup.custom A custom override for the PSQL startup probe.
      custom: {}
    liveness:
      ## @param postgres.probes.liveness.enabled Whether to enable the default PSQL liveness probe.
      enabled: true
      ## @param postgres.probes.liveness.custom A custom override for the PSQL liveness probe.
      custom: {}
    readiness:
      ## @param postgres.probes.readiness.enabled Whether to enable the default PSQL readiness probe.
      enabled: true
      ## @param postgres.probes.readiness.custom A custom override for the PSQL readiness probe.
      custom: {}
  #
  resources:
    #
    requests:
      ## @param postgres.resources.requests.cpu PSQL CPU request.
      cpu: 300m
      ## @param postgres.resources.requests.memory PSQL memory request.
      memory: 512Mi
    #
    limits:
      ## @param postgres.resources.limits.cpu PSQL CPU limit.
      cpu: 700m
      ## @param postgres.resources.limits.memory PSQL memory limit.
      memory: 2Gi
  ## @param postgres.nodeSelector PSQL nodeSelector block.
  nodeSelector: {}
  ## @param postgres.tolerations PSQL tolerations block.
  tolerations: []
  ## @param postgres.affinity PSQL affinity block.
  affinity: {}

## @section Custom Ingress Parameters
##
#
ingress:
  ## @param ingress.enabled Whether to enable the custom Ingress resource.
  enabled: true
  ## @param ingress.className The Ingress class.
  className: traefik
  ## @param ingress.annotations A dict of additional annotations, such as cert-manager Issuers.
  annotations: {}
  ## @param ingress.hostname The hostname for the main and unfiltered admin endpoint. Can be templated.
  hostname: keycloak.{{ .Values.global.domain }}
  ## @param ingress.authHostname The hostname for the limited auth endpoint, used by the Orchestrator. Can be templated.
  authHostname: auth.{{ .Values.global.domain }}
  ## @param ingress.tlsSecret Secret for the TLS credentials. Can be templated.
  tlsSecret: "{{ .Release.Name }}-tls-keycloak"
#
issuer:
  ## @param issuer.enabled Whether to enable the integrated cert-manager Issuer.
  enabled: false
  ## @param issuer.name Overrride for the Issuer name.
  name:
  ## @param issuer.email Email metadata for the Issuer.
  email: example@gmail.com
  ## @param issuer.server Issuing server.
  server: https://acme-v02.api.letsencrypt.org/directory
  ## @param issuer.solvers Override for the Issuer solvers.
  solvers: []

##
## PATCH CONFIGS FOR LEGACY COMPATABILITY.
## The below values should not be edited carelessly.
##
## For more information on the underlying chart, see https://artifacthub.io/packages/helm/bitnami/keycloak/24.7.4.
##
## @skip keycloak Keycloak subchart variables.
keycloak:
  nameOverride: sense-kc
  production: true
  image:
    pullPolicy: Always
  proxy: edge
  postgresql:
    enabled: false
  externalDatabase:
    host: "{{ .Release.Name }}-sense-keycloak-postgres"
    port: 5432
    database: keycloak
    user: keycloak
    existingSecret: "{{ .Release.Name }}-psql-auth"
    existingSecretPasswordKey: password
  tls:
    enabled: false
    autoGenerated: true
  auth:
    adminUser: tempadmin
    existingSecret: "{{ .Release.Name }}-auth"
  service:
    type: ClusterIP
  extraEnvVars:
    - name: KEYCLOAK_EXTRA_ARGS
      value: "--import-realm"
