### SENSE Keycloak Configuration
###

## @section Global Parameters
##
#
global:
  ## @param global.domain The host domain. Can be used for the Ingress hostname such as `keycloak.{{ .Values.global.domain }}`
  domain: example.es.net
  #
  security:
    ## @skip global.security.allowInsecureImages Bitnami image validator.
    allowInsecureImages: true

## @section Common Parameters
##
#
## @param namespaceOverride Override for the Helm namespace.
namespaceOverride:

## @section PostgreSQL Cluster Parameters
##
#
psql:
  ## @param psql.enabled Whether to enable the included CNPG Cluster CRD.
  enabled: true
  ## @param psql.name Custom name for the CNPG Cluster.
  name:
  ## @param psql.username Username to create to own the cluster database.
  username: keycloak
  ## @param psql.database The cluster init database name.
  database: keycloak
  ## @param psql.secret The secret with the database password specified.
  secret: "{{ .Release.Name }}-psql-auth"

## @section Custom Ingress Parameters
##
#
ingress:
  ## @param ingress.enabled Whether to enable the custom Ingress resource.
  enabled: true
  ## @param ingress.className The Ingress class.
  className: traefik
  ## @param ingress.annotations A dict of additional annotations, such as cert-manager Issuers.
  annotations: {}
  ## @param ingress.hostname The hostname for the main and unfiltered admin endpoint. Can be templated.
  hostname: keycloak.{{ .Values.global.domain }}
  ## @param ingress.authHostname The hostname for the limited auth endpoint, used by the Orchestrator. Can be templated.
  authHostname: auth.{{ .Values.global.domain }}
  ## @param ingress.tlsSecret Secret for the TLS credentials. Can be templated.
  tlsSecret: "{{ .Release.Name }}-tls-keycloak"
#
issuer:
  ## @param issuer.enabled Whether to enable the integrated cert-manager Issuer.
  enabled: false
  ## @param issuer.name Overrride for the Issuer name.
  name:
  ## @param issuer.email Email metadata for the Issuer.
  email: example@gmail.com
  ## @param issuer.server Issuing server.
  server: https://acme-v02.api.letsencrypt.org/directory
  ## @param issuer.solvers Override for the Issuer solvers.
  solvers: []

##
## PATCH CONFIGS FOR LEGACY COMPATABILITY.
## The below values should not be edited carelessly.
##
## For more information on the underlying chart, see https://artifacthub.io/packages/helm/bitnami/keycloak/24.7.4.
##
## @skip keycloak Keycloak subchart variables.
keycloak:
  nameOverride: sense-kc
  production: true
  image:
    pullPolicy: Always
  proxy: edge
  postgresql:
    enabled: false
  externalDatabase:
    host: "{{ .Release.Name }}-psql-cluster-rw"
    port: 5432
    database: keycloak
    user: keycloak
    existingSecret: "{{ .Release.Name }}-psql-auth"
    existingSecretPasswordKey: password
  tls:
    enabled: false
    autoGenerated: true
  auth:
    adminUser: tempadmin
    existingSecret: "{{ .Release.Name }}-auth"
  service:
    type: ClusterIP
  extraEnvVars:
    - name: KEYCLOAK_EXTRA_ARGS
      value: "--import-realm"
