apiVersion: batch/v1
kind: Job
metadata:
  name: ${EXPORT_JOB_NAME}
spec:
  backoffLimit: 0
  template:
    spec:
      restartPolicy: Never
      imagePullSecrets: ${KEYCLOAK_IMAGE_PULL_SECRETS}
      containers:
        - name: keycloak-export
          image: ${KEYCLOAK_IMAGE}
          command:
            - /opt/keycloak/bin/kc.sh
            - export
            - --dir
            - /export
            - --verbose
            - --realm
            - ${KEYCLOAK_REALM}
            - --users
            - different_files
            - --users-per-file
            - "100"
          env:
            - name: KC_DB
              value: postgres
            - name: KC_DB_URL_HOST
              value: ${KEYCLOAK_DB_HOST}
            - name: KC_DB_URL_PORT
              value: "${KEYCLOAK_DB_PORT}"
            - name: KC_DB_URL_DATABASE
              value: ${KEYCLOAK_DB_NAME}
            - name: KC_DB_USERNAME
              value: ${KEYCLOAK_DB_USER}
            - name: KC_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: ${KEYCLOAK_DB_SECRET_NAME}
                  key: ${KEYCLOAK_DB_SECRET_KEY}
          volumeMounts:
            - name: export-volume
              mountPath: /export
      volumes:
        - name: export-volume
          persistentVolumeClaim:
            claimName: ${EXPORT_PVC_NAME}
