apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ${EXPORT_PVC_NAME}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ${EXPORT_STORAGE_CLASS}
  resources:
    requests:
      storage: ${EXPORT_STORAGE_SIZE}
