apiVersion: v1
kind: Pod
metadata:
  name: ${EXPORT_READER_NAME}
spec:
  restartPolicy: Never
  containers:
    - name: reader
      image: docker.io/library/busybox@sha256:1487d0af5f52b4ba31c7e465126ee2123fe3f2305d638e7827681e7cf6c83d5e
      command:
        - /bin/sh
        - -c
        - sleep 3600
      volumeMounts:
        - name: export-volume
          mountPath: /export
  volumes:
    - name: export-volume
      persistentVolumeClaim:
        claimName: ${EXPORT_PVC_NAME}
