{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{ include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: keycloak
  annotations:
    {{- if .Values.ingress.annotations }}
    {{ include "common.tplvalues.render" (dict "value" .Values.ingress.annotations "context" $) | nindent 4 }}
    {{- end }}
    {{- if .Values.issuer.enabled }}
    cert-manager.io/issuer: {{ default (printf "%s-issuer" .Release.Name) .Values.issuer.name  }}
    {{- end }}
  name: {{ .Release.Name }}-ingress
spec:
  ingressClassName: {{ .Values.ingress.className | quote }}
  rules:
    - host: {{ (tpl .Values.ingress.adminHostname .) | quote }}
      http:
        paths:
          - backend:
              service:
                name: {{ template "common.names.fullname" .Subcharts.keycloakx }}-http
                port:
                  name: http
            path: /
            pathType: Prefix
    {{- if .Values.ingress.authHostname }}
    - host: {{ (tpl .Values.ingress.authHostname .) | quote }}
      http:
        paths:
          - backend:
              service:
                name: {{ template "common.names.fullname" .Subcharts.keycloakx }}-http
                port:
                  name: http
            path: /realms/StackV/
            pathType: Prefix
          - backend:
              service:
                name: {{ template "common.names.fullname" .Subcharts.keycloakx }}-http
                port:
                  name: http
            path: /admin/realms/StackV/
            pathType: Prefix
          - backend:
              service:
                name: {{ template "common.names.fullname" .Subcharts.keycloakx }}-http
                port:
                  name: http
            path: /resources/
            pathType: Prefix
    {{- end }}
  tls:
    - hosts:
        - {{ (tpl .Values.ingress.adminHostname .) | quote }}
        {{- if .Values.ingress.authHostname }}
        - {{ (tpl .Values.ingress.authHostname .) | quote }}
        {{- end }}
      secretName: {{ (tpl .Values.ingress.tlsSecret .) | quote }}
{{- end }}
