{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "keycloak.fullname" . }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: keycloak
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  annotations:
    {{- if .Values.commonAnnotations }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
    {{- end }}
    {{- if .Values.ingress.annotations }}
    {{- include "common.tplvalues.render" (dict "value" .Values.ingress.annotations "context" $) | nindent 4 }}
    {{- end }}
spec:
  {{- if and .Values.ingress.className (eq "true" (include "common.ingress.supportsIngressClassname" .)) }}
  ingressClassName: {{ .Values.ingress.className | quote }}
  {{- end }}
  rules:
    - host: {{ (tpl .Values.ingress.hostname .) | quote }}
      http:
        paths:
          - backend:
              service:
                name: {{ template "keycloak.fullname" .Subcharts.keycloak }}
                port:
                  name: http
            path: /
            pathType: Prefix
    {{- if .Values.ingress.authHostname }}
    - host: {{ (tpl .Values.ingress.authHostname .) | quote }}
      http:
        paths:
          - backend:
              service:
                name: {{ template "keycloak.fullname" .Subcharts.keycloak }}
                port:
                  name: http
            path: /auth/realms/StackV/
            pathType: Prefix
          - backend:
              service:
                name: {{ template "keycloak.fullname" .Subcharts.keycloak }}
                port:
                  name: http
            path: /auth/admin/realms/StackV/
            pathType: Prefix
          - backend:
              service:
                name: {{ template "keycloak.fullname" .Subcharts.keycloak }}
                port:
                  name: http
            path: /auth/resources/
            pathType: Prefix
    {{- end }}
  tls:
    - hosts:
        - {{ (tpl .Values.ingress.hostname .) | quote }}
        {{- if .Values.ingress.authHostname }}
        - {{ (tpl .Values.ingress.authHostname .) | quote }}
        {{- end }}
      secretName: {{ (tpl .Values.ingress.tlsSecret .) | quote }}
{{- end }}
